# Generated by Django 3.2.5 on 2021-08-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_product_cartitem_produc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='produc',
            new_name='product',
        ),
    ]
